mmmm

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -17,7 +17,7 @@ services:
     environment:
       MONGODB_URI: mongodb://mongo:27017
       DATABASE_NAME: magicstream
-      ALLOWED_ORIGINS: http://localhost
+      ALLOWED_ORIGINS: http://localhost,http://localhost:5173,https://marom-magic.click,http://marom-magic.click
     depends_on:
       - mongo
 
@@ -27,8 +27,28 @@ services:
     container_name: magicstream-frontend
     ports:
       - "80:80"
+      - "443:443"
+    volumes:
+      - ./certs:/etc/nginx/certs:ro
+      - ./certbot/www:/var/www/certbot:ro
+    environment:
+      DOMAIN: marom-magic.click
     depends_on:
       - backend
+
+  certbot:
+    image: certbot/certbot:latest
+    container_name: magicstream-certbot
+    volumes:
+      - ./certs:/etc/letsencrypt
+      - ./certbot/www:/var/www/certbot
+    entrypoint: /bin/sh -c
+    command:
+      - |
+        if [ -z "$${SSL_EMAIL:-}" ]; then
+          echo "SSL_EMAIL is required"; exit 1;
+        fi
+        certbot certonly --webroot -w /var/www/certbot --email "$${SSL_EMAIL}" --agree-tos --no-eff-email --non-interactive -d "$${DOMAIN:-marom-magic.click}" || true
 
 volumes:
   mongo_data:
